# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15-browsers
    steps:
      - checkout
      - run: 
          name: Setup Git
          command: |
            git config -l
            git config user.email circleci@circleci
            git config user.name CircleCI
            git remote --v
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - run: touch environment.local.ts
      - run:
          name: Run tests
          command: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Bump version and Publish
          command: |
            git checkout -- package-lock.json
            npm run release
            git push --tags
            git status
            echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
            npm publish
